### ISSUE TITLE
`for` and `foreach` should be exact aliases of each other

### ISSUE THREAD

**Issue by leonerd** [ganezdragon/tree-sitter-perl#13]
This grammar makes several distinctions between `for` and `foreach`. The real perl parser considers them as *exact* synonyms of each other. Any and all syntax forms that are accepted by one are accepted by the other. Yes; even C-style `for` loops:

```
$ perl -E 'foreach(my $i = 0; $i < 3; $i++) { say $i }'
0
1
2
```

(I can send a PR to fix this)

**Comment by Leeft** [comment]
This is integrated with #27 so this issue can be closed
