### ISSUE TITLE
"quoted" and qq(quoted) strings should be exactly identical

### ISSUE THREAD

**Issue by leonerd** [ganezdragon/tree-sitter-perl#14]
The grammar appears to have different rules for handling a `"quoted"` string, from a `qq(quoted)` one, whereas Perl considers those identical. The two should be handled by the same rules here.

**Comment by ganezdragon** [comment]
actually the main and only difference is the `delimiter`. Double quoted string has `"`, whereas, qq could literally have any ranging from `!`, `{`, etc. So we can't be using the same rule here.
