### ISSUE TITLE
Parser breaks when declaring const string reference to ";"

### ISSUE THREAD

**Issue by danipozo** [ganezdragon/tree-sitter-perl#15]
Parsed correctly:
![image](https://user-images.githubusercontent.com/15173583/161962537-94c0bc2a-1fd6-41ae-8622-56934cdb8349.png)
![image](https://user-images.githubusercontent.com/15173583/161962668-b6fe5636-1b99-4fd9-b4e1-669ddf7cce92.png)
Parsed incorrectly:
![image](https://user-images.githubusercontent.com/15173583/161962771-b30aa803-d874-4a55-8d28-b1c9b8b4dd19.png)

**Comment by ganezdragon** [comment]
@danipozo , I believe you are using the syntax wrongly. Constants in perl would be declared with `use constant` syntax. More info here - https://perldoc.perl.org/constant.

Please feel free to close this issue as needed.

**Comment by oalders** [comment]
Based on that syntax, they might be using `Const::Fast`: https://metacpan.org/pod/Const::Fast

**Comment by ganezdragon** [comment]
@oalders , interesting, let me take a look

**Comment by danipozo** [comment]
> Based on that syntax, they might be using `Const::Fast`: https://metacpan.org/pod/Const::Fast

Yes, that's what I'm using.

**Comment by ganezdragon** [comment]
this is fixed.
