### ISSUE TITLE
Assigning an anonymous subroutine to a hash value breaks the parser

### ISSUE THREAD

**Issue by shdb** [ganezdragon/tree-sitter-perl#17]
The parser breaks after assigning an anonymous subroutine to a hash value.
It happens a soon as something is written inside the curly brackets.

![broken1](https://user-images.githubusercontent.com/61296/166917971-1fe4da1c-b267-4567-a328-8cfa9cf66c72.png)
![broken2](https://user-images.githubusercontent.com/61296/166918645-42c8954c-206e-4906-8095-25ef53420a13.png)
![broken3](https://user-images.githubusercontent.com/61296/166919014-6a4db1bc-7465-4c27-8325-cbfb1f69be58.png)
![ok1](https://user-images.githubusercontent.com/61296/166919136-1e88c32d-d446-4c84-b48b-4529063e1150.png)

**Comment by ganezdragon** [comment]
It seems it breaks not at anonymous subroutines, but on special variables like `$SIG` . Let me look at fixing it.

**Comment by ganezdragon** [comment]
Fixed this in the latest commit. Will publish a newer version soon.
