### ISSUE TITLE
Parser breaks on some heredocs

### ISSUE THREAD

**Issue by lf-** [ganezdragon/tree-sitter-perl#20]
Sample: https://invent.kde.org/sdk/kdesrc-build/-/blob/master/modules/ksb/Updater/Git.pm#L388-399

Somewhat amusingly, gitlab uses treesitter, so it is also broken.

Screenshot:
![image](https://user-images.githubusercontent.com/6652840/183270805-e7f5321c-5e97-4180-8b30-38de94fe211a.png)

All the lines past the end of the screen are also mishighlighted as string.

**Comment by ganezdragon** [comment]
tree-sitter-perl is yet to provide support for eof. Let me see if I can code it this weekend!

**Comment by ganezdragon** [comment]
This is gonna take few more weeks as this is a big feature.

**Comment by ganezdragon** [comment]
this is the feature PR - https://github.com/ganezdragon/tree-sitter-perl/pull/28

**Comment by jimf5** [comment]
> this is the feature PR - #28

This MR is still in progress☹

**Comment by ganezdragon** [comment]
@jimf5 perl heredocs are bit complicated :)

**Comment by jimf5** [comment]
@ganezdragon thanks for your efforts

**Comment by ganezdragon** [comment]
@jimf5 the PR is merged to master. Please check from your end and feel free to close this issue.

**Comment by jimf5** [comment]
@ganezdragon Thank you for fixing this issue. Now heredocs look as it should be.
