### ISSUE TITLE
Broken syntax after a line of code

### ISSUE THREAD

**Issue by brneor** [ganezdragon/tree-sitter-perl#30]
I'm using tree-sitter-perl through [treesitter.nvim](https://github.com/nvim-treesitter/nvim-treesitter) 

```perl
sub mySub {
  my $randomBytes = `head -c 32 /dev/urandom`; # After this line there's no syntax highlighting anymore
  return encode_base64url($randomBytes);
}

sub _log {
  my ($text) = @_;
  print encode_utf8($text) . "\n";
}
```

**Comment by ganezdragon** [comment]
@brneor , backtick quotes aren't supported as of now. Let me work on this soon.

**Comment by ganezdragon** [comment]
this should work now. closing it.

**Comment by brneor** [comment]
@ganezdragon ty for your attention and speed on this one :)
