### ISSUE TITLE
Postfix array size (`$arrayref->$#*`) parses as comment start

### ISSUE THREAD

**Issue by assistcontrol** [ganezdragon/tree-sitter-perl#32]
See attached.

The hash mark in the postfix array size operator (`$arrayref->$#*`) turns the rest of the line into a comment. Is this a `tree-sitter-perl` issue?

![IMG_0068](https://github.com/ganezdragon/tree-sitter-perl/assets/2219761/b8019fbd-7277-410b-8791-b60579da0dc8)

**Comment by ganezdragon** [comment]
let me work on this soon. currently patching heredocs feature in a PR.

**Comment by ganezdragon** [comment]
this should be fixed now :)
