### ISSUE TITLE
parser.c is becoming extremely big

### ISSUE THREAD

**Issue by Wilfred** [ganezdragon/tree-sitter-perl#34]
The size of the generated C parser has reached 70 MiB, which is large for a parser.

There's a little bit of discussion at https://github.com/tree-sitter/tree-sitter/issues/1041 about parser size, but no obvious hints for this repo.

**Comment by ganezdragon** [comment]
@Wilfred , thanks for pointing that out. This is a serious problem, I couldn't even generate a .wasm file in my local machine.

let me go through this, and try to optimize this.

**Comment by ganezdragon** [comment]
currently the parser.c stands at 70MB, and I'm aiming to bring it under < 10MB.

<img width="211" alt="image" src="https://github.com/ganezdragon/tree-sitter-perl/assets/10774943/c7f4f597-84f1-47a7-ab88-9d164bbf34ea">

**Comment by Wilfred** [comment]
@ganezdragon That's a big improvement, thank you :)
