### ISSUE TITLE
Syntax highlighting breaks after a line with string interpolation

### ISSUE THREAD

**Issue by brneor** [ganezdragon/tree-sitter-perl#35]
I'm using tree-sitter-perl through [treesitter.nvim](https://github.com/nvim-treesitter/nvim-treesitter) 

```perl
my $var1 = "This is the value of my first variable";

# If there's anything after '${var1}' inside the double quotes highlighting is broken from this point:
my $var2 = "Content of my first variable is ${var1}!"; 

print('Now evertyhing is broken');
```

**Comment by ganezdragon** [comment]
@brneor this should be working now :) Thanks for reporting it.

**Comment by brneor** [comment]
Yep, it's working indeed. Ty very much!

I've collected some new syntax breaking situations which I'll be reporting on another issue.
