### ISSUE TITLE
Publish to npm Registry

### ISSUE THREAD

**Issue by clemens-mw** [ganezdragon/tree-sitter-perl#42]
Hi, are you planning to also publish this package to the npm Registry?
e.g. like tree-sitter-typescript https://www.npmjs.com/package/tree-sitter-typescript

This would make installing the package much more convenient :)

**Comment by ganezdragon** [comment]
it is published here - https://www.npmjs.com/package/@ganezdragon/tree-sitter-perl

**Comment by clemens-mw** [comment]
Thanks a lot!
