### ISSUE TITLE
When will you release new version?

### ISSUE THREAD

**Issue by ksrnnb** [ganezdragon/tree-sitter-perl#44]
Hello! I want you to ask a question when you will release new version.
In this [issue comment](https://github.com/ganezdragon/tree-sitter-perl/issues/43#issuecomment-2068090974),  you said that `isnumber` problem have been corrected.

But current latest release version v1.1.0, `isnumber` is still used.
https://github.com/ganezdragon/tree-sitter-perl/blob/93bd92a6af01113140f1a0b4c1845d22adae7ab6/src/scanner.c#L549

And in master branch, `isdigit` is used.
https://github.com/ganezdragon/tree-sitter-perl/blob/67720ae81d6565a6c93aa55a6f045e35b417bf65/src/scanner.c#L595

So, I hope new release version is published.

**Comment by ganezdragon** [comment]
let me release a new node version today.. I have been fixing few other things..

**Comment by ganezdragon** [comment]
I have published the new version 1.1.1 :)

**Comment by ksrnnb** [comment]
Thanks!
