### ISSUE TITLE
Tag v1.1.1

### ISSUE THREAD

**Issue by mightyiam** [ganezdragon/tree-sitter-perl#45]
Hey. Thank you for your open source work. Could you please add a git tag for v1.1.1?

#44

**Comment by ganezdragon** [comment]
@mightyiam , I have created a tag for v1.1.1 . Please let me know if I should stop pushing changes directly to master (if that would break something for you), and only push from a PR.

**Comment by ganezdragon** [comment]
or let me release with tags, so that you could point to the tags instead of master directly

**Comment by mightyiam** [comment]
Thank you, @ganezdragon. I recommend automated releases. Consider taking a look at [semantic-release](https://semantic-release.gitbook.io/semantic-release).
