### ISSUE TITLE
Inclusion into nvim-treesitter

### ISSUE THREAD

**Issue by lcrownover** [ganezdragon/tree-sitter-perl#7]
Hey @ganezdragon , 

Do you know when you might PR this into the main [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) repo? Would be cool to have perl support out of the box instead of having to clone and build and configure manually.

[lua/nvim-treesitter/parsers.lua](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/parsers.lua)

**Comment by delphinus** [comment]
Hi, I am also using this with My neovim on trial. I added my highlight .scm here -> https://github.com/lcrownover/nvim-treesitter/pull/1
