### ISSUE TITLE
Syntax highlighting breaks with Mojolicious.

### ISSUE THREAD

**Issue by marcelarie** [ganezdragon/tree-sitter-perl#9]
The syntax breaks in multiple files. Here is [the original issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/1854) I opened at [nvim-treesitter]( 
https://github.com/nvim-treesitter/nvim-treesitter)
![Peek 2021-09-27 12-31](https://user-images.githubusercontent.com/62728887/134892528-b80e8115-42fd-49cc-8e9b-475f82bd1234.gif)

And the regex:
 ```perl
    $tx->res->dom =~ m!"changeLocation":\{"menu":\{"label":\["[^"]+","([0-9]+)"\]\}! && $1;
```
it happens the same with lines like this 
```perl
    if ( my $variations_script = $dom->at( '#twisterJsInitializer_feature_div script' ) ) {
```
where the `#` breaks the syntax. 

I use the last version of nvim nightly and [Mojolicious](https://mojolicious.org/) to work with perl. It seems that the problems are related with the syntax of the library.

**Comment by ganezdragon** [comment]
@marcelarie Thanks for reporting. And yes, this is a issue with grammar. Let me try to fix it this week!

**Comment by xse** [comment]
Hey, might be the same issue where the commented `#` makes "username" blue there:
![2021-11-21 23_35_33-OpenSSH SSH client](https://user-images.githubusercontent.com/183953/142781624-14b7021b-34d5-433f-b02c-00c72803cd96.png)

and without comment:
![2021-11-21 23_36_34-OpenSSH SSH client](https://user-images.githubusercontent.com/183953/142781647-d81b22dc-909e-4757-971d-b642b0143467.png)

```perl
my %config = (
  "foo", {
    "url",  "http://foo.bar",
    "port", "8088", # 8080 default
    "api_key", "",
    "username", "",
    "password", "",
  },
);
```

have a good day!

**Comment by marcelarie** [comment]
> The syntax breaks in multiple files. Here is [the original issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/1854) I opened at [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) ![Peek 2021-09-27 12-31](https://user-images.githubusercontent.com/62728887/134892528-b80e8115-42fd-49cc-8e9b-475f82bd1234.gif)
> 
> And the regex:
> 
> ```perl
>    $tx->res->dom =~ m!"changeLocation":\{"menu":\{"label":\["[^"]+","([0-9]+)"\]\}! && $1;
> ```
> 
> it happens the same with lines like this
> 
> ```perl
>     if ( my $variations_script = $dom->at( '#twisterJsInitializer_feature_div script' ) ) {
> ```
> 
> where the `#` breaks the syntax.
> 
> I use the last version of nvim nightly and [Mojolicious](https://mojolicious.org/) to work with perl. It seems that the problems are related with the syntax of the library.

This still happens.
but the `#` issue does not anymore. :)

**Comment by ganezdragon** [comment]
yea the `#` issue shouldn't happen, or atleast now!

But I'm still working on the regex based patterns in perl. Should release the version soon :)

**Comment by marcelarie** [comment]
Thanks for the work, I can't wait.

**Comment by ganezdragon** [comment]
I have publish version 0.3.0 . This should parse all these syntax properly. Let me know otherwise. :)

**Comment by marcelarie** [comment]
The `m!` syntax is fixed :) Now I realized of the `qr//` highlight error:
![qr-tsperl](https://user-images.githubusercontent.com/62728887/150695524-7c2d7d3c-b4ed-403e-a756-6837d943e16d.gif)

if it's needed I can make a separate issue for that one.

**Comment by ganezdragon** [comment]
@marcelarie , could you paste the expression here ? I can take a look at what's failing.

**Comment by marcelarie** [comment]
> @marcelarie , could you paste the expression here ? I can take a look at what's failing.

Of course, there you go:
```perl
  qr/^@{[ $self->merchant_name ]}$/i
# ^ q making the trouble (?)
  m!"changeLocation":\{"menu":\{"label":\["[^"]+","([0-9]+)"\]\}!
# ^ m making the trouble (?)
```

**Comment by ganezdragon** [comment]
@marcelarie the above patter matcher syntax should be fixed in the latest commit. I will wait around and run some test before publishing the next npm version

**Comment by marcelarie** [comment]
> @marcelarie the above patter matcher syntax should be fixed in the latest commit. I will wait around and run some test before publishing the next npm version

nice, thank you!!

**Comment by brneor** [comment]
`split(/ *, */,$Var)` also breaks syntax highlighting.

**Comment by ganezdragon** [comment]
`split(/ *, */,$Var)` works as expected. And I see the original issue reported here is also fixed. So closing this issue.
